### PR TITLE
Add random response feature

### PR DESCRIPTION
**Pull request by gabrielakoreeda**
Related to issue #7 

Added a new feature: **Sirius response** that returns randomly one of the following possible answers Okay, OK, Okk, Ohk, lol, Nice, Hmm, Noice, Maybe, No, Yes, Yeah.

### CODE REVIEW

**Comment by Legedith** [comment]
Can you make it so it'll keep sending a random response after every text received from the other user.
For example let's say you are conversing with someone named X:
You: Sirius response
X: You wanna know what happened today?
You (Sirius): Yes!
X: I ran into a movie star
You (Sirius): Noice
X: But that wasn't even the craziest part
You (Sirius): Hmmmm
X: That movie star turned out to be my classmate
You (Sirius): No way



I should have specified in the issue, the purpose of this feature is to make Sirius have conversations on your behalf.

**Comment by gabrielakoreeda** [comment]
Sure! I'll work on it!

**Comment by gabrielakoreeda** [comment]
As requested, changed the action to keep replying when a new message comes in. To stop the responses just type the command Sirius response stop

**Comment by Legedith** [comment]
Sweet!

**Pull request merged**
